### PR TITLE
Make aiosession

### PR DESCRIPTION
**Pull request by AlexTheJPEG**
We need to make an aiosession at the beginning of the program so the new ping command can work.

### CODE REVIEW

**Comment by Tymewalk** [comment]
Does this pull request include #26? Or is #26 separate?

**Comment by AlexTheJPEG** [comment]
It does include #26 . I was trying to edit multiple files into one pull request but it turns out I made duplicates. Oh well ¯\\\_(ツ)\_/¯

**Comment by Tymewalk** [comment]
Looking good so far. I'll check it shortly and see if the ping counts the time to open the aiosession as well (that was a problem with one of the previous commits).

**Comment by Tymewalk** [comment]
It's slow (I'm guessing because it has to generate an aiosession) but it properly reports the number of milliseconds. Before it would report 5000ms+, now it's reporting ~100ms (which is a reasonable number.) The only problem now is that it complains of unclosed sessions, so I'll see if I can fix that and then I'll merge.

**Comment by Tymewalk** [comment]
I can't seem to fix it, I tried making it `as session` and then using `session.close()`, but it kept complaining about the session going unclosed. Do you have any ideas?

**Comment by AlexTheJPEG** [comment]
I've done a bunch of research, and from what I've seen, the errors don't really do anything. Maybe try silencing the errors?

**Comment by AlexTheJPEG** [comment]
Try reinstalling the packages `aiohttp` and `websockets` to compatible versions. I tried this and no errors pop up when I terminate the program.

`pip install aiohttp==1.0.5` or any version between `1.0.0` and `1.1.0`
`pip install websockets==3.4` or any version between `3.1` and `4.0`

**Comment by Tymewalk** [comment]
That is weird. It said "requirement already satisfied" when running the commands, but now they run perfectly. No errors when running the command, or when closing the bot.

Looks good, I'll merge. Thanks for the help :smile:

**Pull request merged**
